
default: build

build:
	GOOS=linux go build -ldflags "-s -w" -o bin/create-league-user ./cmd/create-league-user
	GOOS=linux go build -ldflags "-s -w" -o bin/update-league-user ./cmd/update-league-user